language: node_js
node_js: '10'

before_install:
- rvm install 2.5.1

jobs:
  include:
  - stage: test
    script: bash scripts/test-build.sh
  - stage: deploy
    if: type = push
    deploy:
    - provider: script
      on:
        branch: master
      skip_cleanup: true
      script: bash scripts/deploy-master-root.sh
  - stage: deploy
    if: type = push
    deploy:
    - provider: script
      on:
        branch: master
      skip_cleanup: true
      script: bash scripts/deploy-master-version.sh
  - stage: deploy
    if: type = push
    deploy:
    - provider: script
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(feature|release|hotfix)\/*
      skip_cleanup: true
      script: bash scripts/deploy-branch.sh
  - stage: deploy
    if: type = push
    deploy:
    - provider: npm
      email: $NPM_EMAIL_ADDRESS
      api_key: $NPM_AUTH_TOKEN
      on:
        branch: master
        tags: true
      skip_cleanup: true
