language: node_js

before_install:
- rvm install 2.5.1

install:
- pip install --user awscli
- npm install -g gulp-cli

jobs:
  include:
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        branch: feature/HAR-161-s3-deployments # TODO: change to master
      name: Deploy master
      skip_cleanup: true
      script: bash scripts/deploy-master-root.sh
  - script: echo "This is a test"
    node_js: '10'
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        branch: feature/HAR-161-s3-deployments # TODO: change to master
      name: Deploy version
      skip_cleanup: true
      script: bash scripts/deploy-master-version.sh
