language: node_js

before_install:
- rvm install 2.5.1

jobs:
  include:
  - stage: test
	node_js: '10'
    script: bash scripts/test-build.sh
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        branch: master
      skip_cleanup: true
      script: bash scripts/deploy-master-root.sh
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        branch: master
      skip_cleanup: true
      script: bash scripts/deploy-master-version.sh
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^feature\/*
      skip_cleanup: true
      script: bash scripts/deploy-feature.sh
