language: node_js

before_install:
- rvm install 2.5.1

install:
- pip install --user awscli
- npm install -g gulp-cli

jobs:
  include:
  - stage: Test
    script: echo "This is a test"
    node_js:
	- '8'
	- '10'
  - stage: Deploy
    if: type = push
    node_js: '10'
    deploy:
    - provider: script
      on:
        branch: feature/HAR-161-s3-deployments # TODO: change to master
      skip_cleanup: true # TODO: check if this is still needed
      script: bash scripts/deploy-master.sh
