language: node_js

node_js:
- '8'
- '10'

before_install:
- rvm install 2.5.1

install:
- bundle install
- pip install --user awscli
- npm install
- npm install -g gulp-cli
- bash ./scripts/set-package-version-variable.sh

script:
- npm run build
- echo $TRAVIS_EVENT_TYPE
- echo $TRAVIS_COMMIT
- echo $TRAVIS_BRANCH

jobs:
  include:
    - stage: Deploy
      if: type = push
      node_js: '10'
      script:
      - npm run build
      deploy:
        - provider: s3
          on:
            branch: feature/HAR-161-s3-deployments
          bucket: $AWS_BUCKET
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          skip_cleanup: true
          local_dir: ./_gh_pages
          acl: public_read
        - provider: s3
          on:
            branch: feature/HAR-161-s3-deployments
          bucket: $AWS_BUCKET
          access_key_id: $AWS_ACCESS_KEY_ID
          secret_access_key: $AWS_SECRET_ACCESS_KEY
          region: $AWS_REGION
          skip_cleanup: true
          local_dir: ./_gh_pages
          acl: public_read
          upload-dir: '0.0.1'
      after_deploy:
        - aws configure set preview.cloudfront true
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
