language: node_js

node_js:
- '8'
- '10'

before_install:
- rvm install 2.5.1

install:
- bundle install
- pip install --user awscli
- npm install
- npm install -g gulp-cli
- PACKAGE_VERSION=$(cat package.json \ | grep version \ | head -1 \ | awk -F: '{ print $2 }' \ | sed 's/[",]//g')
# Multiple commands, on single line
# PACKAGE_VERSION=$(cat package.json \
# | grep version \
# | head -1 \
# | awk -F: '{ print $2 }' \
# | sed 's/[",]//g')

script: npm run build
# - echo $TRAVIS_EVENT_TYPE
# - echo $TRAVIS_COMMIT

jobs:
  include:
    - stage: Deploy
      node_js: '10'
      script: npm run build
      deploy:
        on:
          branch: feature/HAR-161-s3-deployments
        provider: s3
        bucket: $AWS_BUCKET
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: $AWS_REGION
        skip_cleanup: true
        local_dir: ./_gh_pages
        acl: public_read
      deploy:
        on:
          branch: feature/HAR-161-s3-deployments
        provider: s3
        bucket: $AWS_BUCKET
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: $AWS_REGION
        skip_cleanup: true
        local_dir: ./_gh_pages
        acl: public_read
        upload-dir: $PACKAGE_VERSION
    - stage: After deploy
      after_deploy:
        - aws configure set preview.cloudfront true
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
