# Dependencies
markdown: kramdown
highlighter: rouge

# Settings
source: "site"
destination: ./_gh_pages
keep_files: [css/index.css]
collections_dir: docs
collections:
  components:
    output: true
  controls:
    output: true
  layouts:
    output: true
